---
title: "Knowledge and Reality, Lecture 16"
author: "Brian Weatherson"
date: 2022-10-26
format: 
  beamer: 
    aspectratio: 169
    fontsize: 17pt
#    classoption: handout
    papersize: letter
    navigation: empty
    incremental: true
    innertheme: default
    outertheme: miniframes
    colortheme: wolverine
    mainfont: SF Pro Text Light
    mainfontoptions: BoldFont = SF Pro Text Semibold, Scale = MatchLowercase
    keep-tex: true
    include-in-header:
      text: |
       \captionsetup[figure]{labelformat=empty}
       \usepackage{pgfpages}
       \setbeamertemplate{itemize item}[circle]
       \setbeamertemplate{footline}[frame number]{}
       \mode<handout>{\pgfpagesuselayout{6 on 1}[letterpaper, border shrink=8mm]}
       \AtBeginSection{%
          \begin{frame}
              \tableofcontents[currentsection]
          \end{frame}
       }
---

# Themes

## Two Big Themes

1. What's the importance of the "Anselmian glance", the ability to hold an entire argument in view at once?
2. Is there anything epistemologically special about first-personal reasoning, and if so what is it?

## Hypothesis

These two questions are connected.

- The glance is special because it allows this special kind of first-personal reasoning.

## A Step Back

But why is that?

- The end of the chapter goes over several reasons why we might not care about first-personal reasoning.
- Here's one case where that seems like the right thing to say.

## Fermat's Last Theorem

A famous mathematical problem. Are there positive integers $x, y, z, n$, with $n > 2$, such that

$$
x^n + y^n = z^n
$$

- A few years back, Andrew Wiles (then at Princeton) proved that the answer is no.

## Fermat's Last Theorem

The proof is surprisingly complicated, going through some parts of math that don't look like they have anything to do with the result.

- I haven't made much effort to follow it, and I'm pretty sure I would fail.
- But I now know the theorem is true; people I trust say the proof works.

## Fermat's Last Theorem

Imagine Wiles himself forgets key parts of the proof, and could only reconstruct it by looking back over his notes.

- Question: Is Wiles (in this example, not in reality!) any better placed with respect to Fermat's Last Theorem than the rest of us?

## Fermat's Last Theorem

Pasnau (as I read the end of Ch. 5) wants to say no.

- The fact that he, long ago, did the proof is of no epistemological significance.
- He knows that someone, his younger self, did a proof; but we know that too.
- And there are no other relevant differences between him now, and us now.

## Mathematics and Morality

That seems kind of plausible to me at first glance, at least for this case.

- But I want to talk us through a couple of other cases where it is more plausible that the Anselmian glance matters.

# Moral Testimony

## An Example

Alice and her work colleague Bob are setting down to dinner. Bob says he's thinking of ordering a hambuger, but it's sure whether it is morally ok. Alice says no, meat eating is wrong. Bob has known Alice for a long time, and has a high opinion of her moral judgments. So he orders a salad.

## An Example

- Did that seem strange?
- If so, what was the strangeness?

## One Hypothesis

Moral knowledge only comes from moral reasoning/experience/empathy.

- The problem is that Bob can't know that meat eating is wrong this way.

## Problems for That Hypothesis

Why couldn't Bob get knowledge that way?

- Alice is a reliable testifier, and reliable testimony is a source of knowledge.
- Maybe there is an answer here, but it isn't obvious what it is.

## Another Hypothesis

It's just because this is an extreme case.

- It's weird to not have opinions about meat-eating.
- But we can probably do the same thing with more obscure topics, and it's still a bit weird.

## Oysters

Imagine that Carla and Dave are both vegetarians, and Dave trusts Carla's judgments. At dinner one night, Dave sees Carla eating oysters. He asks her if it's morally ok to eat oysters, and she says yes. Without any more details, he orders oysters.

- Is that weird?

## Third Hypothesis: Understanding

An interesting idea to steer between these views was put forward in the 2000s by Oxford philosopher Alison Hills.

- What goes wrong is that Bob doesn't get moral **understanding**.
- Bob can know this way that meat-eating is wrong (assuming it is!), but can't understand why.

## Mathematics and Morality

At one level, Hills takes mathematics and morality to be alike in these respects.

- Testimony can give you mathematical knowledge (e.g., that Fermat's Last Theorem is true) without mathematical understanding.
- And it can give you moral knowledge without moral understanding.

## Mathematics and Morality

The difference is in how much we (typically) care about these things.

- There is something - though it's hard to say what - sub-optimal about a person who acts on moral knowledge they don't really understand.

## Mathematics and Morality

The difference is in how much we (typically) care about these things.

- But unless you're a math prof, it is fine to know/use/repeat a lot of mathematical claims that you don't understand.

# First Person and the Glance

## About a Glance

In math cases, it is a bit intuitive that the glance is linked to understanding.

- Here's a real-life case (similar to what I've been doing elsewhere in my job) that might help explain it.

## Preference Matching

Here's one thing you have to do in a university department.

- Each year, you work out which courses have to be taught, which rooms are available to teach them in, and which people are available at which times to teach which courses (and how many courses they can teach).
- There are a lot of variables, and there are too many to get a computer to easily scroll through all the options.

## Preference Matching

So we sit down with some combination of pen-and-paper, and computers, to try to get everything to slot into place.

- This usually involves doing something arbritrary for the first few slots (e.g., repeat some things from last year) and fitting the other pieces around like a jigsaw.

## Preference Matching

Imagine one year, we do this, and the last few choices are forced; it looks like there is only one assignment that meets all the constraints. (This is a good year; usually there are 0 and panic ensues.)

- We try it a few different ways, and it's the same result.
- At this point, we know there is only one arrangement of classes/people/times/rooms that works.

## Preference Matching

But that's not the same as **understanding** why there is only one that works.

- If I go back over and see "Oh, Brian has these absurd constraints, and they intersect in weird ways with other constraints, and that's what rules most things out,", now I might understand why there is only one.
- This requires the Anselmian glance.

## Back to Pasnau

Working through these two cases makes me think Pasnau is on to something, though I think I disagree a bit about what he's on to.

- Both the glance, and the first-personal privilege, are related to **understanding**.

## Understanding

With that in mind, let's look at his six way division of options.

# The Six Cases

## Cases A-C

A.  Holding a whole argument in mind at once. 
B.  Holding the conclusion in mind and being able to produce the supporting argument at will. 
C.  Holding the conclusion in mind and being able to produce the supporting argument with effort. 

## Cases D-F

D.  Holding the conclusion in mind and remembering that the supporting argument was once grasped, but no longer being able to produce that argument, even with effort.
E.  Holding the conclusion in mind without any memory of its evidential basis. 
F.  Having forgotten both the conclusion and its supporting argument.

## Two Easy Cases

- A is obviously understanding.
- F is obviously not.

## Mathematics and Morality

I want to spend the rest of the time today going over case from both math and ethics that are between B and E, and asking which of them are really cases of understanding.

## Math Case

We already discussed this: Fermat's Last Theorem.

- But I don't care just about Wiles here.
- Anyone who ever followed the proof, and had something like the Anselmian glance of it, will do.

## Morality Case

Rather than talking about meat-eating in general, imagine someone who basically accepts the argument for ethical vegetarianism, but isn't sure how far it goes.

- In particular, they aren't sure whether oysters are animals in the relevant sense.
- After much research, they decide oysters are not; they are plant-like enough to be ethically eaten.

## Morality Case

And then the later states of them will involve having forgotten, either temporarily or permanently, in whole or in part, the argument for why it was ok to eat oysters.

- When are they just like someone who learns it's ok to eat oysters from a reliable friend?

## My (Tentative) View

The big gap is between C and D.

C. Holding the conclusion in mind and being able to produce the supporting argument with effort. 
D. Holding the conclusion in mind and remembering that the supporting argument was once grasped, but no longer being able to produce that argument, even with effort.

## Case C

- In the math case, this person can tell us the proof, but it takes some time. Still, I think they more-or-less understand why the theorem is true.
- In the morality case, this person can recall which features of oysters make them ok to eat, and why those features matter. That's a big difference from the testimony case.

## Case D

Is this enough for understanding in either case.

- Doesn't seem close to it in the math case; I'd say in that case I used to understand it.
- But maybe, maybe, the morality case is different.

## Two Oyster Examples

- Dave doesn't know anything about oysters, but trusts Carla and takes her word for it that it's ok to eat them.
- Carla had thought about it, and decided it was ok to eat them, but now can't even remember if it was something unexpected about their biology, or a moral distinction she hadn't considered, that made her think that.
- Are these the same?

## Summary

Summary of this class:

- The distinctions that Pasnau starts Ch 5 with are really interesting - as is (as always) the history of them.
- But I think he's a bit negative about their relevance to epistemology.
- They might not be relevant to **knowledge**, but they are relevant to **understanding**.