---
title: "Knowledge and Reality, Quiz 1"
author: "Brian Weatherson"
date: 2022-10-03
format: 
  beamer: 
    aspectratio: 169
    fontsize: 17pt
#    classoption: handout
    papersize: letter
    navigation: empty
    incremental: true
    innertheme: default
    outertheme: miniframes
    colortheme: wolverine
    mainfont: SF Pro Text Light
    mainfontoptions: BoldFont = SF Pro Text Semibold, Scale = MatchLowercase
    keep-tex: true
    include-in-header:
      text: |
       \captionsetup[figure]{labelformat=empty}
       \usepackage{pgfpages}
       \setbeamertemplate{itemize item}[circle]
       \setbeamertemplate{footline}[frame number]{}
       \mode<handout>{\pgfpagesuselayout{6 on 1}[letterpaper, border shrink=8mm]}
       \AtBeginSection{%
          \begin{frame}
              \tableofcontents[currentsection]
          \end{frame}
       }
---

## Question 1

Datta is arguing that testimony is a method of knowledge. One of the objections to this view that he considers is that testimonial knowledge is dependent on other sources, such as perception of the sounds of the speaker. What is his primary reply to this objection?

## True Answer

This argument overgenerates since, for example, inference is also dependent on other sources. We don't just gain inferential knowledge from inferences with zero premises, but from inferences from things learned by testimony or perception, and these are properly classed as inferential.

## False Answer

This argument overgenerates since, for example, perception is also dependent on other sources such as inference. We can't get perceptual knowledge without relying on our background knowledge that are perceptual faculties are reliable, and then inferring that they are working on this occasion.

## Why is False Answer False

- Datta does not think perception relies on inference.
- And he certainly doesn't say this in the paper.
- If he thought it did, he arguably wouldn't think that it is a method of knowing in the relevant sense.

## Question 3

What is the "Approved List" response to BonJour's example of Norman the clairvoyant, which is meant to be a counterexample to reliabilism.

## True Answer

Although Norman is justified in his beliefs, people mistakenly think he is not, since they usually judge justification by asking whether the belief was formed by a process that they think is reliable in the real world.

## False Answer

Norman is not a counterexample since reliabilism says that justified beliefs are those obtained by a process known to be reliable, and Norman doesn't know that his powers are reliable.

## Why is False Answer False

- Reliabilism does not require that processes are known to be reliable.
- Everyone (more or less) thinks you can get knowledge from processes known to be reliable.
- What's distinctive about reliabilism is that you don't need this knowldge; fact of reliability can be enough.

## Question 4

Why do they [Ichikawa and Steup] say that the "No False Lemmas" analysis fails?

## True Answer

Because in cases like the robot dog, there is no knowledge, but no reasoning from a false lemma.

## False Answer

Because in cases like the robot dog, there is knowledge even though there is reasoning from a false lemma.

- Here it's just a matter of checking whether there is knowledge in the robot dog case, and they say there isn't.

## Essay

A good 300-level philosophy essay does three things.

1. Say what question the person you're writing about is asking.
2. Say what their answer is.
3. Evaluate that answer.

## Essay

The evaluation need not be enormous, and can't be in the length involved.

- An example where the answer seems to go wrong would do.
- An application of the answer to a separate problem, to either bring out its strengths or weaknesses, would also do.

## Essay

For 1500-2000 words, I don't expect you to be writing a **research** paper.

- You can get top grades without reading anything that's not on the syllabus.
- But you do have to read the stuff that is on the syllabus, including the recommended readings for the topics you're writing on, **closely**.


